




CREATE TABLE permissions(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(500)
);

CREATE TABLE roles(
    id BIGINT AUTO_INCREMENT,
    name VARCHAR(100),
    CONSTRAIN fk_tid_role FOREIGN KEY  REFERENCES
)

CREATE TABLE user_role