CREATE TABLE tenants
(
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    cnpj VARCHAR(14) NOT NULL UNIQUE ,
    email VARCHAR(256) NOT NULL UNIQUE ,
    razao_social VARCHAR(150) NOT NULL ,
    nome_fantasia VARCHAR(150) NOT NULL ,
    associates VARCHAR(255) DEFAULT null,
    phone VARCHAR(20),


    plan ENUM('ENTERPRISE','SCALING','INICIAL','FREE') DEFAULT 'FREE',
    status ENUM('ACTIVE','INACTIVE','DELETED','PENDENT','BLOCKED') DEFAULT 'ACTIVE',
    demo BOOLEAN DEFAULT FALSE,

    register_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE users ADD
    CONSTRAINT fk_tenant_id
        FOREIGN KEY (tenant_id)
        REFERENCES tenants(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE;
