ALTER TABLE users RENAME TO employees;

ALTER TABLE employees
    ADD salary DECIMAL(10,2) NOT NULL,
    ADD cpf VARCHAR(11) NOT NULL,
    ADD hire_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD roles varchar(100) DEFAULT NULL,
    ADD full_name TEXT NOT NULL,
    ADD phone VARCHAR(11) NOT NULL;

